project:
    type: website
    output-dir: ../

website:
    title: "AI 101"
    sidebar:
        contents: auto
    search: true
    page-navigation: true

subtitle: "AI 101"

format:
    html:
        toc: true
        theme: darkly 
        code-line-numbers: true
        code-tools:
            source: true
            toggle: false
            caption: none
    revealjs: 
        theme: dark
        slide-number: true
        show-slide-number: all
        width: 1050
        height: 700
        footer: "[Home](index.html)"
        output-ext: rjs.html        